# Generated by Django 5.0.7 on 2024-07-29 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_alter_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('transaction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('close_date', models.DateTimeField(blank=True, null=True)),
                ('reference_number', models.CharField(max_length=100)),
                ('ship_to_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ship_to_company', models.CharField(blank=True, max_length=100, null=True)),
                ('ship_to_address', models.CharField(blank=True, max_length=200, null=True)),
                ('ship_to_address2', models.CharField(blank=True, max_length=200, null=True)),
                ('ship_to_city', models.CharField(blank=True, max_length=100, null=True)),
                ('ship_to_state', models.CharField(blank=True, max_length=50, null=True)),
                ('ship_to_zip', models.CharField(blank=True, max_length=20, null=True)),
                ('ship_to_country', models.CharField(blank=True, max_length=50, null=True)),
                ('weight_lb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('line_items', models.IntegerField(blank=True, null=True)),
                ('sku_quantity', models.JSONField(blank=True, null=True)),
                ('total_item_qty', models.IntegerField(blank=True, null=True)),
                ('volume_cuft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('packages', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('carrier', models.CharField(blank=True, max_length=50, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
