# Generated by Django 5.1.5 on 2025-02-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_priority_order_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderSKUView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.IntegerField()),
                ("reference_number", models.CharField(max_length=100)),
                ("sku_name", models.CharField(max_length=100)),
                ("sku_count", models.IntegerField()),
            ],
            options={
                "db_table": "orders_sku_view",
                "managed": False,
            },
        ),
    ]
