# Generated by Django 5.1.6 on 2025-02-14 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_add_order_search_indexes"),
        ("orders", "0003_orderskuview"),
    ]

    operations = []
