# Generated by Django 5.1.6 on 2025-02-16 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_orderservice"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrderService",
        ),
    ]
