# Generated by Django 5.1.4 on 2024-12-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_services', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerservice',
            name='skus',
            field=models.ManyToManyField(blank=True, related_name='customer_services', to='products.product'),
        ),
    ]
