# Generated by Django 5.1.6 on 2025-02-09 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_services", "0002_customerservice_skus"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerServiceView",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("customer_service", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "customer_service_view",
                "managed": False,
            },
        ),
    ]
