# Generated by Django 5.1 on 2024-09-13 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_services", "0001_initial"),
        ("rules", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RuleGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logic_operator",
                    models.CharField(
                        choices=[
                            ("AND", "All conditions must be true (AND)"),
                            ("OR", "Any condition can be true (OR)"),
                            ("NOT", "Condition must not be true (NOT)"),
                            ("XOR", "Only one condition must be true (XOR)"),
                            ("NAND", "At least one condition must be false (NAND)"),
                            ("NOR", "None of the conditions must be true (NOR)"),
                        ],
                        default="AND",
                        max_length=5,
                    ),
                ),
                (
                    "customer_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer_services.customerservice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        choices=[
                            ("reference_number", "Reference Number"),
                            ("ship_to_name", "Ship To Name"),
                            ("ship_to_company", "Ship To Company"),
                            ("ship_to_city", "Ship To City"),
                            ("ship_to_state", "Ship To State"),
                            ("ship_to_country", "Ship To Country"),
                            ("weight_lb", "Weight (lb)"),
                            ("line_items", "Line Items"),
                            ("sku_quantity", "SKU Quantity"),
                            ("total_item_qty", "Total Item Quantity"),
                            ("packages", "Packages"),
                            ("notes", "Notes"),
                            ("carrier", "Carrier"),
                            ("volume_cuft", "Volume (cuft)"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("gt", "Greater than"),
                            ("lt", "Less than"),
                            ("eq", "Equals"),
                            ("ne", "Not equals"),
                            ("ge", "Greater than or equals"),
                            ("le", "Less than or equals"),
                            ("in", "In"),
                            ("ni", "Not in"),
                            ("contains", "Contains"),
                            ("ncontains", "Not contains"),
                            ("startswith", "Starts with"),
                            ("endswith", "Ends with"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="For multiple values, separate them with a semicolon (;)",
                        max_length=255,
                    ),
                ),
                (
                    "adjustment_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount to adjust the price",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "rule_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="rules.rulegroup",
                    ),
                ),
            ],
        ),
        # Removed migrations.DeleteModel operation
    ]