# Generated by Django 5.1.4 on 2024-12-11 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_rulegroup_rule_delete_billingcriteria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingCriteria',
        ),
    ]
