# Generated by Django 5.1.4 on 2025-01-04 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0003_delete_billingcriteria'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedRule',
            fields=[
                ('rule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rules.rule')),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('calculations', models.JSONField(blank=True, default=list)),
            ],
            bases=('rules.rule',),
        ),
    ]
