# Generated by Django 5.1.4 on 2025-01-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0005_alter_advancedrule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='operator',
            field=models.CharField(choices=[('gt', 'Greater than'), ('lt', 'Less than'), ('eq', 'Equals'), ('ne', 'Not equals'), ('ge', 'Greater than or equals'), ('le', 'Less than or equals'), ('in', 'In'), ('ni', 'Not in'), ('contains', 'Contains'), ('ncontains', 'Not contains'), ('only_contains', 'Only contains'), ('startswith', 'Starts with'), ('endswith', 'Ends with')], max_length=15),
        ),
    ]
