# Generated by Django 5.1.4 on 2025-01-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0006_alter_rule_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancedrule',
            name='calculations',
            field=models.JSONField(blank=True, default=list, help_text="Calculation steps as JSON: [{'type': 'calculation_type', 'value': number}]"),
        ),
        migrations.AlterField(
            model_name='advancedrule',
            name='conditions',
            field=models.JSONField(blank=True, default=dict, help_text="Additional conditions as JSON: {'field': {'operator': 'value'}}"),
        ),
        migrations.AlterField(
            model_name='rule',
            name='operator',
            field=models.CharField(choices=[('gt', 'Greater than'), ('lt', 'Less than'), ('eq', 'Equals'), ('ne', 'Not equals'), ('ge', 'Greater than or equals'), ('le', 'Less than or equals'), ('in', 'In'), ('ni', 'Not in'), ('contains', 'Contains'), ('ncontains', 'Not contains'), ('only_contains', 'Only Contains'), ('startswith', 'Starts with'), ('endswith', 'Ends with')], max_length=15),
        ),
    ]
