# Generated by Django 5.1.5 on 2025-02-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0007_alter_advancedrule_calculations_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="field",
            field=models.CharField(
                choices=[
                    ("reference_number", "Reference Number"),
                    ("ship_to_name", "Ship To Name"),
                    ("ship_to_company", "Ship To Company"),
                    ("ship_to_city", "Ship To City"),
                    ("ship_to_state", "Ship To State"),
                    ("ship_to_country", "Ship To Country"),
                    ("sku_count", "SKU Count"),
                    ("sku_name", "SKU Name"),
                    ("sku_quantity", "SKU Quantity"),
                    ("total_item_qty", "Total Item Quantity"),
                    ("packages", "Packages"),
                    ("notes", "Notes"),
                    ("carrier", "Carrier"),
                    ("volume_cuft", "Volume (cuft)"),
                    ("weight_lb", "Weight (lb)"),
                    ("line_items", "Line Items"),
                ],
                max_length=50,
            ),
        ),
    ]
