# Generated by Django 5.1 on 2024-09-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='charge_type',
            field=models.CharField(choices=[('single', 'Single Charge'), ('quantity', 'Quantity Based')], default='quantity', max_length=10),
        ),
    ]
