# Generated by Django 5.0.7 on 2024-07-29 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_alter_customer_id'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CADShipping',
            fields=[
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='orders.order')),
                ('service_code_description', models.CharField(blank=True, max_length=255, null=True)),
                ('ship_to_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ship_to_address_1', models.CharField(blank=True, max_length=255, null=True)),
                ('ship_to_address_2', models.CharField(blank=True, max_length=255, null=True)),
                ('shiptoaddress3', models.CharField(blank=True, max_length=255, null=True)),
                ('ship_to_city', models.CharField(blank=True, max_length=255, null=True)),
                ('ship_to_state', models.CharField(blank=True, max_length=255, null=True)),
                ('ship_to_country', models.CharField(blank=True, max_length=255, null=True)),
                ('ship_to_postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=50, null=True)),
                ('pre_tax_shipping_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax1type', models.CharField(blank=True, max_length=50, null=True)),
                ('tax1amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax2type', models.CharField(blank=True, max_length=50, null=True)),
                ('tax2amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax3type', models.CharField(blank=True, max_length=50, null=True)),
                ('tax3amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fuel_surcharge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('box_length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('box_width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('box_height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('box_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ship_date', models.DateTimeField(blank=True, null=True)),
                ('carrier', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_ship_date', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='USShipping',
            fields=[
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='orders.order')),
                ('ship_date', models.DateField(blank=True, null=True)),
                ('ship_to_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ship_to_address_1', models.CharField(blank=True, max_length=255, null=True)),
                ('ship_to_address_2', models.CharField(blank=True, max_length=255, null=True)),
                ('ship_to_city', models.CharField(blank=True, max_length=255, null=True)),
                ('ship_to_state', models.CharField(blank=True, max_length=255, null=True)),
                ('ship_to_zip', models.CharField(blank=True, max_length=20, null=True)),
                ('ship_to_country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=50, null=True)),
                ('service_name', models.CharField(blank=True, max_length=255, null=True)),
                ('weight_lbs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('length_in', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('width_in', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('height_in', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('base_chg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('carrier_peak_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('wizmo_peak_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('accessorial_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_status', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_status', models.CharField(blank=True, max_length=255, null=True)),
                ('first_attempt_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('days_to_first_deliver', models.IntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
