# Generated by Django 5.1.6 on 2025-02-16 07:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0004_customer_is_active"),
        ("orders", "0006_delete_orderservice"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingCalculationCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.IntegerField()),
                ("customer_id", models.IntegerField()),
                ("customer_service_id", models.IntegerField()),
                ("service_name", models.CharField(max_length=100)),
                ("charge_type", models.CharField(max_length=10)),
                ("billing_type", models.CharField(max_length=10)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("sku_quantity", models.JSONField(null=True)),
                ("product_details", models.JSONField(null=True)),
                ("rules", models.JSONField(null=True)),
            ],
            options={
                "db_table": "billing_calculation_cache",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BillingServiceRate",
            fields=[
                (
                    "customer_service_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("customer_id", models.IntegerField()),
                ("service_id", models.IntegerField()),
                ("service_name", models.CharField(max_length=100)),
                ("charge_type", models.CharField(max_length=10)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("assigned_skus", models.JSONField(null=True)),
                ("billing_type", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "billing_service_rates",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OrderBillingDetail",
            fields=[
                (
                    "transaction_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("customer_id", models.IntegerField()),
                ("close_date", models.DateTimeField()),
                ("sku_quantity", models.JSONField(null=True)),
                ("total_item_qty", models.IntegerField(null=True)),
                ("status", models.CharField(max_length=20)),
                ("product_details", models.JSONField(null=True)),
            ],
            options={
                "db_table": "order_billing_details",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ServiceRuleEvaluation",
            fields=[
                ("customer_service_id", models.IntegerField()),
                (
                    "rule_group_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("logic_operator", models.CharField(max_length=10)),
                ("rules", models.JSONField()),
            ],
            options={
                "db_table": "service_rule_evaluation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BillingReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("report_data", models.JSONField()),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Billing Report",
                "verbose_name_plural": "Billing Reports",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="BillingReportDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_breakdown", models.JSONField()),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.order"
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="billing.billingreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Billing Report Detail",
                "verbose_name_plural": "Billing Report Details",
            },
        ),
    ]
