# Generated by Django 5.0.7 on 2024-07-28 22:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_rename_customers_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=100)),
                ('labeling_unit_1', models.CharField(blank=True, max_length=50, null=True)),
                ('labeling_quantity_1', models.PositiveIntegerField(blank=True, null=True)),
                ('labeling_unit_2', models.CharField(blank=True, max_length=50, null=True)),
                ('labeling_quantity_2', models.PositiveIntegerField(blank=True, null=True)),
                ('labeling_unit_3', models.CharField(blank=True, max_length=50, null=True)),
                ('labeling_quantity_3', models.PositiveIntegerField(blank=True, null=True)),
                ('labeling_unit_4', models.CharField(blank=True, max_length=50, null=True)),
                ('labeling_quantity_4', models.PositiveIntegerField(blank=True, null=True)),
                ('labeling_unit_5', models.CharField(blank=True, max_length=50, null=True)),
                ('labeling_quantity_5', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('sku', 'customer'), name='billing_product_sku_customer_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('labeling_quantity_1__gte', 0)), name='billing_product_labeling_quantity_1_check'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('labeling_quantity_2__gte', 0)), name='billing_product_labeling_quantity_2_check'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('labeling_quantity_3__gte', 0)), name='billing_product_labeling_quantity_3_check'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('labeling_quantity_4__gte', 0)), name='billing_product_labeling_quantity_4_check'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('labeling_quantity_5__gte', 0)), name='billing_product_labeling_quantity_5_check'),
        ),
    ]
